### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [gary9630/TeaCozy#4]
Overall met expectations. 

You did a good job matching the website spec. Everything was well organized and setup properly.

Your focus should be more gear to best practices in organization and efficiency.

The location div positioning is minor but it needed to be pointed out.

I also typically looked for unneeded css which is why pointed out the flex wrap usage.

As a challenge use media queries to make this site look like a mobile app on a mobile device.

This will help prepare you for the upcoming projects as they will be having use media queries quite frequently.

**Comment by gary9630** [comment]
OK~got it~!! Thank you for your review!!
